services:
  - type: web
    name: unfake
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    autoDeploy: true 