services:
  - type: web
    name: unfake
    env: python
    buildCommand: |
      export PATH="/opt/render/project/poetry/bin:$PATH" &&
      curl -sSL https://install.python-poetry.org | python3 - &&
      poetry config virtualenvs.create true &&
      poetry config virtualenvs.in-project true &&
      poetry install
    startCommand: |
      export PATH="/opt/render/project/poetry/bin:$PATH" &&
      /opt/render/project/poetry/bin/poetry run gunicorn wsgi:app --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    autoDeploy: true 