services:
  - type: web
    name: unfake
    env: python
    buildCommand: |
      python3 -m pip install --upgrade pip &&
      python3 -m pip install -r requirements.txt
    startCommand: |
      python3 -m gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /
    autoDeploy: true 